export const GET_QUESTIONS = "GET_QUESTIONS";
export const CREATE_NEW_QUIZ = "CREATE_NEW_QUIZ";
export const ADD_QUESTION_TO_CHOOSEN_QUIZ = "ADD_QUESTION_TO_CHOOSEN_QUIZ";
export const REMOVE_QUESTION_FROM_QUIZ = "REMOVE_QUESTION_FROM_QUIZ";
